#!/bin/bash

### root or not ###
if [ `id -u` -ne 0 ]
then
echo "Run this script in root user only"
exit
fi
### root or not end ###


##Installing Updated on the server##

read -p "---> Installing System Updates (y/n)?" choice
case "$choice" in
  y|Y ) yum -y update;;
  n|N ) echo "no";;
  * ) echo "invalid";;
esac

##Installing Nginx on the server##

echo -n "---> Installing Nginx on server?  [y/n][y]:"
	read message_yes
if [ "${message_yes}" == "y" ];then
read -p "IPADDRESS of the Server :" IPADDRESS
rpm -ivh nginx/nginx-release-centos-6-0.el6.ngx.noarch.rpm
yum -y update
yum -y install nginx
cp nginx/50x.html /var/www/html/
cp nginx/index.html  /var/www/html/
cp nginx/info.php /var/www/html/
cp nginx/newvirtual.conf /etc/nginx/conf.d/
sed -i "s/DOMAINNAME/${IPADDRESS}/g" /etc/nginx/conf.d/newvirtual.conf
/etc/init.d/nginx start
    else
echo no
  fi

##Installing PHP-5.6 on the server##

 echo -n "---> Installing PHP5.6 on server?  [y/n][y]:"
    read terms_agree
  if [ "${terms_agree}" == "y" ];then
rpm -Uvh php56/remi-release-6*.rpm php56/epel-release-6*.rpm
cp /etc/yum.repos.d/remi.repo /etc/yum.repos.d/remi.repo_org
sed -i '/\[remi-php56\]/,/^ *\[/ s/enabled=0/enabled=1/' /etc/yum.repos.d/remi.repo
yum -y update
yum -y install php php-cli php-common php-fpm php-gd php-curl php-mbstring php-bcmath php-soap php-mcrypt php-mysql php-xml php-pecl-memcache php-pecl-redis php-opcache php-pecl-geoip
/etc/init.d/php-fpm restart
chkconfig php-fpm on
chkconfig httpd off
/etc/init.d/nginx restart
chkconfig nginx on 
        else
echo no
  fi

##Installing IonCube Loader for php5.6 on the server##

 echo -n "---> Installing IonCube Loader for php5.6 on server?  [y/n][y]:"
    read loaders
  if [ "${loaders}" == "y" ];then
cp ioncube/ioncube_loader_lin_5.6.so /usr/lib64/php/modules/
chmod 755 /usr/lib64/php/modules/ioncube_loader_lin_5.6.so
cp /etc/php.ini /etc/php.ini_org
echo "zend_extension = /usr/lib64/php/modules/ioncube_loader_lin_5.6.so"  >> /etc/php.ini
/etc/init.d/php-fpm restart
/etc/init.d/nginx restart
        else
echo no
  fi

##Installing Percona Mysql 5.5 on the server##

 echo -n "---> Installing Percona Mysql 5.5 on server?  [y/n][y]:"
    read database
  if [ "${database}" == "y" ];then
yum -y remove mysql-*
rpm -ivh mysql_percona_5.6/percona-release-0.1-3.noarch.rpm
yum -y update
yum -y install Percona-Server-server-56
service mysql start
/usr/bin/mysql_secure_installation
else
    exit 1
  fi

